### ISSUE TITLE
[factorization] External packages should be optional

### ISSUE THREAD

**Issue by mesnardo** [barbagroup/PetIBM#106]
External packages such as yaml-cpp, Boost, gtest, and AmgXWrapper should be optional and not present in the PetIBM repository.

When a package is already installed on the machine, we should give the possibility to the use to use it. This feature should be made available at configuration time with the command-line argument `--with-PACKAGE-dir=PATH`.

In the case where the package is not (correctly) installed, we should provide the feature of downloading and installing it at configuration time with a command-line argument like `--download-PACKAGE`.

**Comment by piyueh** [comment]
Waiting for GitHub to automatically close this issue. This should have been fixed in #99.
