### ISSUE TITLE
Clean up stale branches?

### ISSUE THREAD

**Issue by piyueh** [barbagroup/PetIBM#118]
Do we have to clean up those stale branches on GitHub?

**Comment by mesnardo** [comment]
It seems like a good idea, it will make the repo cleaner.
All branches, except `master`, `develop`, and `factorization`, could be removed.
Sounds good?

**Comment by piyueh** [comment]
Yes. I believe the features of most of the branches are either merged or can be found in old releases.

**Comment by piyueh** [comment]
Done.
