### ISSUE TITLE
[factorization] Change LICENSE type and header docs in all source files

### ISSUE THREAD

**Issue by piyueh** [barbagroup/PetIBM#121]
* Change LICENSE type to BSD
* Change header docs in all source files

**Comment by labarba** [comment]
MIT License:  
> “The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.” 

BSD 3-clause:  
> “Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.”

This language implies that a user could copy _some_ of an MIT-licensed code (as long as the portion is deemed "not substantial") without attribution. In academia, we always prefer full attribution of any portions of copied works, and BSD 3-clause is more precise in this.
