### ISSUE TITLE
Ability of handling structures with no thickness, such as a membrane

### ISSUE THREAD

**Issue by shi-guangyu** [barbagroup/PetIBM#148]
Hi, guys,

Many thanks for making this amazing code open-source. I'm working on the aerodynamics of flapping membrane, which is structurally a surface with no thickness. I'm wondering if PetIBM is able to handle that at the moment. From my understanding, it may need some special treatments at the wall boudnary condition.

Many thanks in advance.

Guangyu

**Comment by piyueh** [comment]
Pinging @mesnardo

**Comment by mesnardo** [comment]
Hi @shi-guangyu 

PetIBM can compute the flow around a body with zero thickness, only if it's a rigid body (no deformation).
We are not doing anything special regarding the boundary condition on the surface, apart from enforcing a no-slip condition.
For a zero-thickness surface, the regularized delta function spread the Lagrangian forces on both sides.
We have an [example](https://github.com/barbagroup/PetIBM/tree/master/examples/decoupledibpm/flatplate3dRe100AoA30_GPU) for a 3D flow around an inclined flat plate that you could try.

Let me know if you have further questions.

**Comment by shi-guangyu** [comment]
Hi, @mesnardo ,

Thanks a lot for your rely. Since it can deal with rigid plate with no thickness, it can handle a membrane with prescribed deformation as long as I write some code defining this deformation via the provided API. Am I correct?

With best wishes;

Guangyu

**Comment by mesnardo** [comment]
You are correct.
And I would also recommend remeshing the Lagrangian surface as it deforms.
In my experience, I found that body forces are less prone to spurious oscillations when the Lagrangian resolution is similar to the Eulerian resolution (background grid on which the fluid equations are solved).

**Comment by shi-guangyu** [comment]
Question solved! Thank you very much, Mesnardo. I'll try some examples to see how it goes. Will leave a message if have further problems.

All the best!

Guangyu

**Comment by mesnardo** [comment]
Excellent! Closing this issue for now but feel free to re-open it if you have further related questions. All the best!
