### ISSUE TITLE
figures cannot be saved with python scripts

### ISSUE THREAD

**Issue by shi-guangyu** [barbagroup/PetIBM#152]
Hi, guys,

I found that the python script used to plot the data couldn't save the plotted figure in ./figures directory. I checked the script and found that it plots the figure before saving it. So I just moved the pyplot.show() to the end of the script so the figure can be saved before being shown.

It's just a minor issue of post-processing, but I think it's worth pointing it out.

Kind regards;

Guangyu

**Comment by piyueh** [comment]
@shi-guangyu I couldn't reproduce the issue. I was testing with `examples/decoupledibpm/cylinder2dRe550_GPU/scripts/plotVorticity.py` and `examples/decoupledibpm/cylinder2dRe550_GPU/scripts/plotDragCoefficient.py`. Are these the scripts used in this issue?

In my test, the figures popped up first, and then after I closed the figures, they are saved to `examples/decoupledibpm/cylinder2dRe550_GPU/figures`. I launched the Python scripts from the simulation folder. In other words, I execute `python scripts/plotVorticity.py` under `examples/decoupledibpm/cylinder2dRe550_GPU/`.

**Comment by shi-guangyu** [comment]
Yes, you're right. The figures can be saved automatically now. It's kind of weired. It may because I just updated the scipy and numpy, I met some problems with the compatibility of the two previously.

Sorry for that.

Best wishes;

Guangyu
