### ISSUE TITLE
[Probes] attributes "count" is written to duplicated path

### ISSUE THREAD

**Issue by piyueh** [barbagroup/PetIBM#157]
At [line 565 in `probes.cpp`](https://github.com/barbagroup/PetIBM/blob/ef82cd969bd70bd04741fb999fb00555db836536/src/misc/probes.cpp#L565), an attribute, `count`, is written to `root/field/field/time`.

@mesnardo Is this intentional? Or is it supposed to be written to `root/field/time`? (The `viewer` object at this line is already under `root/field` when calling this function.)

For example, if the field is `p`, and if the HDF5 file is read into `data`, then the `count` attribute of time `10.0` will be at:
```data["p"]["p"]["10.000000"].attrs["count"]```
according to our current implementation at [line 565 in `probes.cpp`](https://github.com/barbagroup/PetIBM/blob/ef82cd969bd70bd04741fb999fb00555db836536/src/misc/probes.cpp#L565).

**Comment by mesnardo** [comment]
Good catch! No need to have this extra `field` (i.e., can be moved to one node up). `count` represents the number of time-steps over which the data were accumulated.
