### ISSUE TITLE
[PETSc] Upgrade to match PETSc v3.13.2+

### ISSUE THREAD

**Issue by piyueh** [barbagroup/PetIBM#158]
`DMDA_X`, `DMDA_Y`, `DMDA_Z`, and the enum type `DMDADirection` do not exist anymore in PETSc 3.13.2. Previously, they are defined in `petscdmda.h`. Not sure when PETSc team removed them.

In PETSc 3.13.2, there's a new enum type called `DMDirection`. And it provides `DM_X`, `DM_Y`, and `DM_Z`. I haven't looked into what these are. But my hunch says they are drop-in replacements of `DMDA_X`, `DMDA_Y`, and `DMDA_Z`.

**Comment by mesnardo** [comment]
Upgraded to PETSc 3.16+ in [PetIBM v0.5.3](https://github.com/barbagroup/PetIBM/releases/tag/v0.5.3). Done in #160
