### ISSUE TITLE
Write script to plot force coefficients

### ISSUE THREAD

**Issue by anushkrish** [barbagroup/PetIBM#37]

**Comment by mesnardo** [comment]
The script `plotForces.py` (folder: `scripts/python/`) reads the forces (not the force coefficients) from text file `forces.txt` and displays the figure using `matplotlib`.

**Comment by mesnardo** [comment]
Script: `plotForceCoefficients.py`.

The command-line flag `--coefficient` followed by a force-to-coefficient value does the job.

For example:

```bash
python $PETIBM_DIR/scripts/python/plotForceCoefficients.py --coefficient 2.0
```
