### ISSUE TITLE
Spatial convergence and observed rate of convergence for TGV

### ISSUE THREAD

**Issue by mesnardo** [barbagroup/PetIBM#52]
The unit-test for the explicit convective term exhibits 2nd-order convergence in space:
![convergenceconvectiveterm2d](https://cloud.githubusercontent.com/assets/5657080/7303583/ac354256-e9bf-11e4-97e0-3a4f58e93e5e.png)

The unit-test for the explicit diffusive term exhibits an order of convergence less than 2.0, due to the Dirichlet boundary condition (and because PetIBM is not using ghost-cells at physical boundaries):
![convergencediffusiveterm2d](https://cloud.githubusercontent.com/assets/5657080/7303625/f89c4d06-e9bf-11e4-9805-89195f920954.png)
When we ignore the solution from the nodes that are the closest to the physical boundaries, we get 2nd-order convergence.

For the cavity-flow case (Re=100), the observed orders of convergence are:
- grids: 60x60, 180x180, 540x540:
  - u-velocity: 1.7893
  - v-velocity: 1.5949
  - pressure: 1.7702
- grids: 90x90, 270x270, 810x810:
  - u-velocity: 1.8627
  - v-velocity: 1.8822
  - pressure: 1.9501

For the Taylor-Green vortex case, where we have an analytical solution for the 2d case, the observed orders of convergence are (using the last three grids):
- grids: 20x20, 60x60, 180x180, 540x540:
  - u-velocity: 0.4977
  - v-velocity: 0.4977
  - pressure: 1.9995
    ![grid_convergence_last_three](https://cloud.githubusercontent.com/assets/5657080/7303812/1ad21a26-e9c1-11e4-8867-9ad637303e39.png)
- grids: 25x25, 75x75, 225x225, 675x675:
  - u-velocity: -0.3729
  - v-velocity: -0.3729
  - pressure: 1.9996
    ![grid_convergence_last_three](https://cloud.githubusercontent.com/assets/5657080/7303865/55f8a566-e9c1-11e4-9834-424ee1f134d8.png)
- grids: 30x30, 90x90, 270x270, 810x810:
  - u-velocity: -0.7340
  - v-velocity: -0.7340
  - pressure: 2.0000
    ![grid_convergence_last_three](https://cloud.githubusercontent.com/assets/5657080/7303881/7f3e31a2-e9c1-11e4-8568-595d4fde9865.png)

The two-dimensnional Taylor-Green vortex case uses periodic boundary conditions in both directions. 
So, we would be expecting 2nd-order convergence.

To be investigated.

**Comment by anushkrish** [comment]
Can you also write a unit test for the Poisson solver with Neumann boundary conditions?

Also, can you make sure you use very small tolerances for the Navier-Stokes tests? Try relative tolerances of 1e-8 to 1e-10 for both the velocity and the pressure linear solvers. Those results look bizarre - I'm not able to think of why they should look like that apart from using high tolerances in the computation.

**Comment by mesnardo** [comment]
Those results were run with a relative tolerance of `1.0E-08` for both solvers. 

I just tried to use `rtol=1.0E-12` this morning on the `20x20` series, and got exactly the same behavior observing the following orders of convergence:
* u: 0.4978
* v: 0.4978
* p: 1.9998

**Comment by mesnardo** [comment]
## The test-case: 2d lid-driven cavity flow

We want to show that the Navier-Stokes solver implemented in PetIBM is second-order accurate in space in the absence of an immersed boundary.

We choose the test-case of the two-dimensional lid-driven cavity flow. The top side of the unit-square cavity ([0, 1]x[0, 1]) moves with speed 1.0 in the x-direction. The Reynolds number, based on the lid-speed , the cavity side-length, and the kinematic viscosity, is set to 100.0.

To investigate the spatial order of convergence, we compute the solution on five grids consecutively refined with a ratio of 3: 20x20, 60x60, 180x180, 540x540, and 1620x1620.

For each simulation, we compute $500$ time-steps with time-increment 5.0E-04. The convective terms and the diffusive terms are treated explicitly and implicitly, respectively.

All spatial derivatives are approximated with second-order accurate central differences.

We choose to solve the velocity with a biconjugate-gradient stabilized that is diagonally preconditioned. We fix the exit criterion of the solver with an absolute tolerance of 1.0E-12.
For the Poisson system, we use a conjugate-gradient algorithm with a GAMG preconditioner. The solver is said to have convergence when the absolute residual is smaller than 1.0E-12.

We repeated the simulations using cuIBM, another code that implements the method but uses the library CUSP to iteratively solve the systems on GPU.

We compute the observed order of convergence in space using the solution on three consecutive grids in the L2-norm.

## The observation: PetIBM orders do not match cuIBM ones

The table below reports the orders of convergence for the velocity components (u and v) and the pressure (p) observed with PetIBM (first row) and cuIBM (second row).
The suffix ("first", "middle", or "last") refers to the trio of grids used to compute the observed order:
* "first": 20x20, 60x60, and 180x180;
* "middle": 60x60, 180x180;, and 540x540;
* "last": 180x180, 540x540, and 1620x1620.

| time-step | u-first | u-middle | u-last | v-first | v-middle | v-last | p-first | p-middle | p-last |
|---|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
| 500 | 1.7704 | 2.1153 | -0.3919 | 1.5688 | 2.0317 | 0.7289 | 1.5684 | 1.964 | 1.8199 |
| 500 | 1.7695 | 2.116 | 1.9837 | 1.5663 | 2.037 | 1.9341 | 1.5703 | 1.9638 | 1.8206 |

The results for the velocity variables obtained with PetIBM do not match the cuIBM ones when using the "last" trio of grids to compute the orders. 
However, the orders for the pressure variable are similar.

The figures below show the differences in the solution, after 500 time-steps, between a grid and the finest grid when solving with PetIBM (top) and cuIBM (bottom).

![petibm_single_cavity_gridconvergence0000500](https://cloud.githubusercontent.com/assets/5657080/14162926/85d0959a-f6be-11e5-8ce8-114daa5b030d.png)

![cuibm_cavity_gridconvergence0000500](https://cloud.githubusercontent.com/assets/5657080/14162929/8eed571c-f6be-11e5-9ca1-28321fc13699.png)

We observe second-order convergence for the Navier-Stokes solver implemented in cuIBM, but not PetIBM's one (see "hockey stick" as the grid-spacing becomes smaller).

As this point, I ran various series of simulations using different input parameters. 
I modified the solver tolerances (both absolute and relative), the preconditioner, the solver algorithm, and the temporal scheme for the convective and diffusive terms.
In addition, I ran a series only using one process (serial) to make sure the numerical solution was not altered.
Still, I was not getting second-order convergence with PetIBM.

I also ran other test-cases that do not involve wall boundaries. 
The Taylor-Green vortex and the problem of translating vortices (inviscid case suggested by Gil). 
These two test-cases use periodic boundary conditions in all directions.
Again, the observed order of convergence for the velocity components were wrong (unexpected) when using the finest trio of grids.

Going back to the lid-driven cavity flow, I ran a series with a finer starting grid-size (30x30).
The other refined grids are: 90x90, 270x270, 810x810, and 2430x2430.
The table below reports the orders of convergence for the velocity components and the pressure observed with PetIBM (first row) and cuIBM (second row).

| time-step | u-first | u-middle | u-last | v-first | v-middle | v-last | p-first | p-middle | p-last |
|---|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
| 500 | 1.7449 | 1.8801 | -1.0029 | 1.5569 | 1.9926 | -0.0989 | 1.6193 | 1.9708 | 1.8657 |
| 500 | 1.7451 | 2.1251 | 1.9679 | 1.5554 | 2.0122 | 1.9448 | 1.6193 | 1.9706 | 1.8638 |

This time we report divergence in the results when using the middle and the last trio.

## The turnover: fluxes versus velocity-components

I decided to have a close look at the numerical solution generated by both codes. 
I compared the velocity values along various horizontal and vertical gridlines to check where the PetIBM solution diverged from the cuIBM one.
The figures just below show two intervals of the y-velocity profile along an horizontal gridline at mid-cavity. The purple line is the cuIBM solution and the blue-dotted line shows the PetIBM solution.

![cavity_yvelocity_midhorizontalgridline](https://cloud.githubusercontent.com/assets/5657080/14162937/a9f3ae4e-f6be-11e5-8158-ed6d1a7a4706.png)

![cavity_yvelocity_midhorizontalgridline_2](https://cloud.githubusercontent.com/assets/5657080/14162939/b170d3ae-f6be-11e5-8d0b-6b6cf7e073e3.png)

The PetIBM profile is oscillating while the cuIBM one remains smooth. 
These oscillation are responsible for the degradation in the spatial order of convergence of the velocity components.

However, if we look at the flux profiles (see figure below for the y-flux along an horizontal gridline at mid-cavity), the oscillations disappear and the PetIBM solution matches the cuIBM one.

![cavity_yflux_midhorizontalgridline](https://cloud.githubusercontent.com/assets/5657080/14162955/c048a384-f6be-11e5-9739-03f098881832.png)

Moreover, the observed-order of convergence for the fluxes is very close to 1.0 (which is expected as the flux is defined as the velocity times the cell-side, thus depends on the grid-spacing).

In PetIBM and cuIBM, we solve a system for the fluxes that are then saved into files. 
During post-processing stage, we convert the fluxes into velocity components using a Python script and the grid-nodes coordinates available in the file `grid.txt` generated by PetIBM.
Thus, observing the conversion of the fluxes into velocity-components introduces oscillations, we end-up with two possibilities: there is either a bug in the Python script or a bug in the way the grid-nodes are written into a file in PetIBM.


## The verdict

PETSc was built in double precision.
Thus, a variable of type `PetscReal` is double precision.
In PetIBM, we wrote the grid-nodes into a file with the function `std::ofstream`. 
By default, the nodes are written with only 6 digits of precision.
With only 6 digits to describe the nodal locations, we may loose some information when converting the fluxes into velocity-components.
During our convergence study, as we refined the grid, the grid-spacing becomes smaller and smaller, and this truncation has a greater effect on the solution.
We now understand why the observed orders of PetIBM and cuIBM were similar when using the first and middle trio of grids, and diverged with the trio of finest grids.

We can modify PetIBM code to increase the precision of the stream with `std::setprecision` when writing the grid-nodes into file.

The table below reports the orders of convergence for the velocity components and the pressure observed with the modified version of PetIBM (first row) and cuIBM (second row).

| time-step | u-first | u-middle | u-last | v-first | v-middle | v-last | p-first | p-middle | p-last |
|---|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
| 500 | 1.7695 | 2.116 | 1.9836 | 1.5663 | 2.037 | 1.9341 | 1.5684 | 1.964 | 1.8199 |
| 500 | 1.7695 | 2.116 | 1.9837 | 1.5663 | 2.037 | 1.9341 | 1.5703 | 1.9638 | 1.8206 |

The observed orders of convergence from PetIBM match those obtained with cuIBM.
As expected, the Navier-Stokes solver implemented in PetIBM is second-order in space.

For the Taylor-Green vortex and the translating vortices problems (that involves periodic boundary conditions in all directions), the observed orders are even closer to 2. (PetIBM does not use ghost-cells, so that the stencil-width for the diffusive terms is modified at the boundaries that have a wall-condition.)
