### ISSUE TITLE
An error occured when using PETSc 3.6.1: ‘PetscOptionsObject’ was not declared in this scope

### ISSUE THREAD

**Issue by piyueh** [barbagroup/PetIBM#59]
I got this error in NavierStokesSolver<dim>::helpers(). PETSc version is 3.6.1.
There is an issue describing this problem in others' codes: https://github.com/pism/pism/issues/322

**Comment by piyueh** [comment]
See: https://github.com/pism/pism/commit/58c4e5b3748127ffa4aea35f44487a6a85dcb4c9

**Comment by gforsyth** [comment]
That issue seems to have been resolved by Petsc 3.6.1 -- are you still having the issue with that version?

**Comment by piyueh** [comment]
Solution: Add `PetscOptionsBegin(...)` and `PetscOptionsEnd()` before and after `PetscOptionsBool(...)` . I'll submit a pull request for this.
