### ISSUE TITLE
[PETSc 3.6.1] Regression Tests failed when comparing to results using PETSc 3.5.4

### ISSUE THREAD

**Issue by piyueh** [barbagroup/PetIBM#62]
1. Lid driven cases diverge. PETSc complained about the GAMG preconditioners are indefinite. If we use ilu or block Jacobi as preconditioners, they converge.
2. Cylinder flows converge with GAMG preconditioners but can not pass regression tests, which compare the results with those using PETSc 3.5.4 and use a criteria of `1.0E-06`.  Only when we adjust the criteria to `1.0E-03`, cylinder flows pass the regression tests.

**Comment by piyueh** [comment]
Differences in output regarding the gamg preconditioner may give us some hints?

* using PETSc 3.5:

---------------------------
PC Object:(poisson_) 2 MPI processes
&nbsp;&nbsp;&nbsp;&nbsp;type: gamg
&nbsp;&nbsp;&nbsp;&nbsp;PC has not been set up so information may be incomplete
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;MG: type is MULTIPLICATIVE, levels=0 cycles=unknown
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cycles per PCApply=0
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Using Galerkin computed coarse grid matrices

------------------------------

* using PETSc 3.6: 

----------------------------------
PC Object:(poisson_) 2 MPI processes
&nbsp;&nbsp;&nbsp;&nbsp;type: gamg
&nbsp;&nbsp;&nbsp;&nbsp;PC has not been set up so information may be incomplete
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;MG: type is MULTIPLICATIVE, levels=0 cycles=unknown
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cycles per PCApply=0
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Using Galerkin computed coarse grid matrices
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;GAMG specific options
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Threshold for dropping small values from graph 0
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AGG specific options
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Symmetric graph false

--------------------------------------------

**Comment by piyueh** [comment]
Using `-poisson_pc_gamg_threshold <value>` with value larger or equal to `0.5`, lid driven cases don't complain the indefinite preconditioner. Everything goes fine.

But regression tests of lid driven case still don't get passed, even we use the same threshold with both PETSc 3.5 and 3.6 versions.

**Comment by gforsyth** [comment]
What about a regression test where both 3.5 and 3.6 are using ILU?

**Comment by gforsyth** [comment]
Regression tests pass using petsc-3.6-compatible compiled against petsc master on git (as of commit b19ca9c) compared against base results from branch develop compiled against petsc 3.5.4

According to [this exchange on petsc-users](http://lists.mcs.anl.gov/pipermail/petsc-users/2015-September/027170.html) there was a problem with GAMG that caused the error.  

For whatever reason, GAMG was using GMRES inside the multigrid solver which [as Barry noted](http://lists.mcs.anl.gov/pipermail/petsc-users/2015-September/027166.html) doesn't work.  

Not sure if this will have any effect on #53 or not, but I'm closing this issue out.

**Comment by piyueh** [comment]
For 2D lid driven with Re=100 in our examples, if I use one process, everything goes fine, but if I use more than 1 processes (e.g. `mpiexec -np 2 bin/petibm2d -directory examples/2d/lidDrivenCavity/Re100`), it fails.

**Comment by gforsyth** [comment]
which mpi are you using?

**Comment by piyueh** [comment]
OpenMPI 1.10.0

**Comment by gforsyth** [comment]
can you try with mpich?

**Comment by piyueh** [comment]
We have moved on to PETSc 3.8.1, so the existence of this issue in current PetIBM is unclear.
