### ISSUE TITLE
PETSC_CONF_PATH in examples/Makefile.am is incorrect

### ISSUE THREAD

**Issue by gforsyth** [barbagroup/PetIBM#65]
commit ec4426da added 
```
include @PETSC_CONF_PATH@/variables
```

but `PETSC_CONF_PATH` is configured as $PETSC_DIR/$PETSC_ARCH and the examples are looking for either

```
/$PETSC_DIR/lib/petsc/conf/variables
```
for 3.6.1

or

```
/$PETSC_DIR/conf/variables
```
for 3.5.4

**Comment by piyueh** [comment]
`PETSC_CONF_PATH` is set to be the path of `conf` folder, and the `variables` is always located under the `conf` folder no matter it's PETSc 3.5 or 3.6, so `@PETSC_CONF_PATH@/variables` should find `variables`.  At least in my computer it works for both PETSc 3.5 and 3.6.

**Comment by gforsyth** [comment]
there are two `conf` folders.  `@PETSC_CONF_PATH@` finds the one that lives in `$PETSC_DIR/$PETSC_ARCH/lib/petsc/conf` or `$PETSC_DIR/$PETSC_ARCH/conf`for 3.6 and 3.5, respectively.  but `variables` (not `petscvariables`) only exists in `$PETSC_DIR/lib/petsc/conf` or `$PETSC_DIR/conf`.  At least that's the case on theo and phantom

**Comment by piyueh** [comment]
I see.  So even there are several different `PETSC_ARCH` under `$PETSC_DIR`, the `conf` is still directly under `$PETSC_DIR`, am I correct ?

**Comment by gforsyth** [comment]
Well, there is still a `conf` under `$PETSC_ARCH` that I imagine reflects differences in the compile configuration, but the file `variables` only lives in the `conf` file under `$PETSC_DIR`

**Comment by piyueh** [comment]
Did you install PETSc to other directory after compilation, like `/opt` or `/usr`, using `configure --prefix=...`?  Or you just use the directory containing PETSc source codes as the `$PETSC_DIR`?

**Comment by gforsyth** [comment]
just into the PETSc source directory

**Comment by piyueh** [comment]
I see. Then that's the reason why on Yeager it works.  Because I always install PETSc to other location after compilation.  The structure of the PETSc library folder will be different.

**Comment by gforsyth** [comment]
i'll install PETSc into `/opt` and see if everything still runs as expected

**Comment by piyueh** [comment]
You can also try on Yeager. There are already PETSc installations in `/opt`.  `/opt/PETSc` is version 3.6; `/opt/PETSc35` is version 3.5.

**Comment by gforsyth** [comment]
Ahh -- so when you install PETSc to a prefix, it ignores/removes `$PETSC_ARCH` from the path.  My fix works on both installation scenarios, although we can probably implement it in a simpler way, like @mesnardo did on the develop branch.
