### ISSUE TITLE
Write grid nodes in binary files

### ISSUE THREAD

**Issue by mesnardo** [barbagroup/PetIBM#73]
When running spatial convergence tests, an issue related to the IO method to write the grid nodes into file was discovered.
We could not observe second-order convergence in space for the Navier-Stokes solver because the precision at which the grid nodes were written was not big enough.

As a workaround, we increased the number of digits (and we finally got the expected second-order behavior).

We could also write the grid nodes into a binary file to not loose any information.

**Comment by piyueh** [comment]
@mesnardo I think in factorization branch we won't have this problem: we use HDF5 instead of ASCII, so the coordinates should have enough precision.

We should close this issue once we merge the factorization branch into the master branch. Right now, I'm going to put a "done" label on this issue.
