### ISSUE TITLE
PETSc 3.7 support

### ISSUE THREAD

**Issue by piyueh** [barbagroup/PetIBM#75]
I'm going to make the code compatible with PETSc 3.7.3, because PETSc 3.5 is 2-year old now.

**Comment by Haider-BA** [comment]
Installation procedure is same as before?

**Comment by mesnardo** [comment]
The installation procedure should not be that different.
You can have a look at the [installation instructions](https://github.com/barbagroup/PetIBM/blob/feature-compatible-petsc-3.7/doc/installation.md) of PetIBM with PETSc-3.7.x.
