### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Haider-BA** [barbagroup/PetIBM#78]
Hi, I am installing petIBM using petsc 3.7.4 and getting the following error when configuring petibm. The director name is 3.5.2 but it contains 3.7.4 version of petsc.

`==================================
# Configuring required package PETSc

configure: using PETSC_DIR: /home/user/sfw/petsc/3.5.2
configure: using PETSC_ARCH: linux-opt
grep: /home/user/sfw/petsc/3.5.2/linux-opt/conf/petscvariables: No such file or directory
grep: /home/user/sfw/petsc/3.5.2/linux-opt/conf/petscvariables: No such file or directory
grep: /home/user/sfw/petsc/3.5.2/linux-opt/conf/petscvariables: No such file or directory
checking petsc.h usability... no
checking petsc.h presence... no
checking for petsc.h... no
configure: error: could not find header file petsc.h
`

Regards

**Comment by mesnardo** [comment]
With PETSc-3.7.x, you should switch to the branch `feature-compatible-petsc-3.7`. 
(There is an open PR #77  to be merged into `develop`.)
The `master` branch is only compatible with PETSc-3.5.x.

**Comment by mesnardo** [comment]
The branch `master` and the release 0.2 are compatible with PETSc-3.7.
