### ISSUE TITLE
How to run multi-body simulation?

### ISSUE THREAD

**Issue by Haider-BA** [barbagroup/PetIBM#79]
How we can run multi-body simulations for example 2D circular cylinder in a tandem arrangement?

**Comment by mesnardo** [comment]
Right now, the code does not properly support multiple immersed boundaries in the sense that it is not able to compute the hydrodynamic forces acting on each individual body.
Also note that the code only handles fixed rigid boundaries.

However, if you are just interested in the flow around multiple bodies, you can store all the Lagrangian points in the same body file (in which the first line stores the total number of Lagrangian points).

We should implement multiple moving boundaries for the next release. Another issue #30 requested this enhancement.

**Comment by Haider-BA** [comment]
@mesnardo:  Are multi-body simulations implemented now?

**Comment by mesnardo** [comment]
PetIBM now supports multiple fixed immersed boundaries for the IBPM (Immersed Boundary Projection Method) and its decoupled version.
We still do not have moving-boundaries capability in place.
