### ISSUE TITLE
compiler warnings with gcc 6.3.1

### ISSUE THREAD

**Issue by dodol** [barbagroup/PetIBM#95]
You are probably aware of this: When compiling the PetIBM with gcc 6.3.1 I get lots of compiler warnings for the use of auto_ptr, since it's been flagged as deprecated - that is, the -Wdeprecated-declarations compiler flag triggers the warning.

**Comment by piyueh** [comment]
Hi dodol,
Sorry for late reply. Yes, you are right. I think most of those warnings come from yaml-cpp library. We are looking forward to a new release of yaml-cpp and hope they will convert all `auto_ptr`s to `shared_ptr` or `unique_ptr`.
